# Generated by Django 4.2.6 on 2023-10-14 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acmeHomeInsurancePricing', '0002_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=40)),
                ('value', models.FloatField()),
                ('is_multiplier', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='StateMultipliers',
        ),
        migrations.AddField(
            model_name='quoterules',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acmeHomeInsurancePricing.state'),
        ),
    ]
