# Generated by Django 4.2.6 on 2023-10-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmeHomeInsurancePricing', '0006_quoterule_on_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterule',
            old_name='rule',
            new_name='rule_name',
        ),
    ]
