# Generated by Django 4.2.6 on 2023-10-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmeHomeInsurancePricing', '0007_rename_rule_quoterule_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rules',
            field=models.CharField(default={}, max_length=200),
            preserve_default=False,
        ),
    ]
