# Generated by Django 4.2.6 on 2023-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmeHomeInsurancePricing', '0008_quote_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='rules',
            field=models.CharField(max_length=400),
        ),
    ]
