# Generated by Django 4.2.6 on 2023-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmeHomeInsurancePricing', '0009_alter_quote_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='owner_name',
            field=models.CharField(default='testname', max_length=40),
            preserve_default=False,
        ),
    ]
