# Generated by Django 4.2.6 on 2023-10-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmeHomeInsurancePricing', '0010_quote_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='id',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
