# Generated by Django 4.2.6 on 2023-10-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmeHomeInsurancePricing', '0011_remove_quote_id_quote_quote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_id',
        ),
        migrations.AddField(
            model_name='quote',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
